ALTER WORKLOAD SYSDEFAULTUSERWORKLOAD COLLECT ACTIVITY DATA NONE;

ALTER SERVICE CLASS SYSDEFAULTSUBCLASS UNDER SYSDEFAULTUSERCLASS COLLECT AGGREGATE ACTIVITY DATA NONE;

SET EVENT MONITOR DB2ACTIVITIES STATE 0;

DELETE FROM ACTIVITY_DB2ACTIVITIES;
DELETE FROM ACTIVITYSTMT_DB2ACTIVITIES;
DELETE FROM ACTIVITYVALS_DB2ACTIVITIES;
DELETE FROM ACTIVITYMETRICS_DB2ACTIVITIES

CALL WLM_COLLECT_STATS();
